// Colour palette adopted from http://vis.stanford.edu/color-names/analyzer/

var coColorPalette = {
    country: {
        AUSTRALIA: "#c49c94",
        CHINA: "#ff7f0e",
        GERMANY: "#d62728",
        "HONG KONG": "#ffbb78",
        INDONESIA: "#e377c2",
        IRAQ: "#f7b6d2",
        NETHERLAND: "#ff9896",
        "SAUDI ARABIA": "#9467bd",
        SINGAPORE: "#2ca02c",
        "SOUTH KOREA": "#7f7f7f",
        SWITZERLAND: "#8c564b",
        UAE: "#aec7e8",
        "UNITED KINGDOM": "#98df8a",
        "UNITED STATES": "#1f77b4",
        UNSPECIFIED: "#c5b0d5"
    },
    commodity: {
        "ANIMAL OR VEGETABLE FATS AND OILS AND THEIR CLEAVAGE PRODUCTS; PRE. EDIBLE FATS; ANIMAL OR VEGETABLE WAXEX.":
            "#ff9896",
        "ARTICLES OF APPAREL AND CLOTHING ACCESSORIES, NOT KNITTED OR CROCHETED.":
            "#c49c94",
        "COTTON.": "#ff7f0e",
        "ELECTRICAL MACHINERY AND EQUIPMENT AND PARTS THEREOF; SOUND RECORDERS AND REPRODUCERS, TELEVISION IMAGE AND SOUND RECORDERS AND REPRODUCERS,AND PARTS.":
            "#ff7f0e",
        "FERTILISERS.": "#9467bd",
        "IRON AND STEEL": "#98df8a",
        "MINERAL FUELS, MINERAL OILS AND PRODUCTS OF THEIR DISTILLATION; BITUMINOUS SUBSTANCES; MINERAL WAXES.":
            "#1f77b4",
        "NATURAL OR CULTURED PEARLS,PRECIOUS OR SEMIPRECIOUS STONES,PRE.METALS,CLAD WITH PRE.METAL AND ARTCLS THEREOF;IMIT.JEWLRY;COIN.":
            "#aec7e8",
        "NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHANICAL APPLIANCES; PARTS THEREOF.":
            "#ffbb78",
        "OPTICAL, PHOTOGRAPHIC CINEMATOGRAPHIC MEASURING, CHECKING PRECISION, MEDICAL OR SURGICAL INST. AND APPARATUS PARTS AND ACCESSORIES THEREOF;":
            "#c5b0d5",
        "ORGANIC CHEMICALS": "#2ca02c",
        "PHARMACEUTICAL PRODUCTS": "#c49c94",
        "PLASTIC AND ARTICLES THEREOF.": "#d62728",
        "VEHICLES OTHER THAN RAILWAY OR TRAMWAY ROLLING STOCK, AND PARTS AND ACCESSORIES THEREOF.":
            "#8c564b"
    }
};
